# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnProduct = QtWidgets.QPushButton(self.centralwidget)
        self.btnProduct.setGeometry(QtCore.QRect(310, 40, 141, 31))
        self.btnProduct.setObjectName("btnProduct")
        self.btnIssue = QtWidgets.QPushButton(self.centralwidget)
        self.btnIssue.setGeometry(QtCore.QRect(310, 70, 141, 31))
        self.btnIssue.setObjectName("btnIssue")
        self.btnCompany = QtWidgets.QPushButton(self.centralwidget)
        self.btnCompany.setGeometry(QtCore.QRect(310, 100, 141, 31))
        self.btnCompany.setObjectName("btnCompany")
        self.btnState = QtWidgets.QPushButton(self.centralwidget)
        self.btnState.setGeometry(QtCore.QRect(310, 130, 141, 31))
        self.btnState.setObjectName("btnState")
        self.lineState = QtWidgets.QLineEdit(self.centralwidget)
        self.lineState.setGeometry(QtCore.QRect(450, 130, 169, 31))
        self.lineState.setObjectName("lineState")
        self.lineCompany = QtWidgets.QLineEdit(self.centralwidget)
        self.lineCompany.setGeometry(QtCore.QRect(450, 99, 169, 31))
        self.lineCompany.setObjectName("lineCompany")
        self.lineIssue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineIssue.setGeometry(QtCore.QRect(450, 69, 169, 31))
        self.lineIssue.setObjectName("lineIssue")
        self.lineProduct = QtWidgets.QLineEdit(self.centralwidget)
        self.lineProduct.setGeometry(QtCore.QRect(450, 39, 169, 31))
        self.lineProduct.setObjectName("lineProduct")
        self.BtnZipcode = QtWidgets.QPushButton(self.centralwidget)
        self.BtnZipcode.setGeometry(QtCore.QRect(310, 160, 141, 31))
        self.BtnZipcode.setObjectName("BtnZipcode")
        self.lineZipcode = QtWidgets.QLineEdit(self.centralwidget)
        self.lineZipcode.setGeometry(QtCore.QRect(450, 160, 169, 31))
        self.lineZipcode.setObjectName("lineZipcode")
        self.btnProduct_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnProduct_2.setGeometry(QtCore.QRect(160, 350, 141, 31))
        self.btnProduct_2.setObjectName("btnProduct_2")
        self.lineProduct_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineProduct_2.setGeometry(QtCore.QRect(300, 350, 169, 31))
        self.lineProduct_2.setObjectName("lineProduct_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnProduct.setText(_translate("MainWindow", "Product"))
        self.btnIssue.setText(_translate("MainWindow", "Issue"))
        self.btnCompany.setText(_translate("MainWindow", "Company"))
        self.btnState.setText(_translate("MainWindow", "State"))
        self.BtnZipcode.setText(_translate("MainWindow", "ZIP code"))
        self.btnProduct_2.setText(_translate("MainWindow", "Senaryo 1"))
